name: 'Run Tests'
description: 'Run tests for halos-browser-trust (shellcheck only)'

runs:
  using: 'composite'
  steps:
    - name: Run shellcheck
      run: shellcheck debian/postinst debian/postrm
      shell: bash
