name: Release Published

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  apt-publish:
    uses: halos-org/shared-workflows/.github/workflows/apt-publish.yml@380f7729bbacab699ae89dfd5296eaaafcb9afcb # v1 candidate
    with:
      channel: stable
      apt-repository: halos-org/apt.halos.fi
      apt-distro: trixie
      apt-component: main
    secrets:
      APT_REPO_PAT: ${{ secrets.APT_REPO_PAT }}
