name: Release Published

on:
  release:
    types: [published]

jobs:
  apt-publish:
    uses: halos-org/shared-workflows/.github/workflows/apt-publish.yml@8e0a559ed3cd1307b35b103579ee2fd5633e40d3 # feat/v1-release-pipeline
    with:
      channel: stable
      apt-repository: halos-org/apt.halos.fi
      apt-distro: trixie
      apt-component: main
    secrets:
      APT_REPO_PAT: ${{ secrets.APT_REPO_PAT }}
